// src/App.jsx
import React, { Component, Fragment } from 'react'

class App extends Component {
  constructor(props) {
    super(props)

    this.state = {
      from: '',
      message: '',
      signature: '',
      accounts: [],
      error: false,
    }
    this.checkWeb3 = this.checkWeb3.bind(this)
    this.errorNotification = this.errorNotification.bind(this)
    this.sign = this.sign.bind(this)
    this.personalSign = this.personalSign.bind(this)
    this.verify = this.verify.bind(this)
    this.reset = this.reset.bind(this)
    this.requestAccount = this.requestAccount.bind(this)
  }

  componentDidMount() {
    Notification.requestPermission()

    this.checkWeb3()
  }

  checkWeb3() {
    if (!window.web3) {
      this.setState({
        ...this.state,
        error: true,
      })
      return
    }

    if (web3.eth.accounts.length === 0) {
      console.info(
        'Your web3 has not any accounts. Enter some manually or request it.'
      )
      return
    }

    this.setState({
      ...this.state,
      accounts: web3.eth.accounts || [],
    })
  }

  errorNotification() {
    /* eslint-disable */
    new Notification('Action denied', {
      body: 'An error occured, see console for more details',
    })
    /* eslint-enable */
  }

  verify() {
    const { message, signature } = this.state

    web3.currentProvider.sendAsync(
      {
        method: 'personal_ecRecover',
        params: [message, signature],
      },
      (err, { result }) => {
        if (err) {
          this.errorNotification()
          console.error(err)
          return
        }

        alert(`Recovered address: ${result}`)
      }
    )
  }

  sign() {
    const { from, message } = this.state

    web3.currentProvider.sendAsync(
      {
        method: 'eth_sign',
        params: [from, web3.toHex(message)],
      },
      (err, { result }) => {
        if (err) {
          this.errorNotification()
          console.error(err)
          return
        }

        this.setState({
          ...this.state,
          signature: result,
        })
      }
    )
  }

  personalSign() {
    const { from, message } = this.state

    web3.currentProvider.sendAsync(
      {
        method: 'personal_sign',
        params: [from, web3.toHex(message)],
      },
      (err, { result }) => {
        if (err) {
          this.errorNotification()
          console.error(err)
          return
        }

        this.setState({
          ...this.state,
          signature: result,
        })
      }
    )
  }

  requestAccount() {
    web3.currentProvider.sendAsync(
      {
        method: 'eth_accounts',
        params: [],
      },
      (err, { result }) => {
        if (err) {
          this.errorNotification()
          console.error(err)
          return
        }

        this.setState({
          ...this.state,
          accounts: result,
          from: result[0],
        })
      }
    )
  }

  reset() {
    this.setState({
      ...this.state,
      message: '',
      signature: '',
    })
  }

  onChangeInputByName(name) {
    return e => {
      this.setState({
        ...this.state,
        [name]: e.target.value,
      })
    }
  }

  renderWeb3Error() {
    return <h1>Web3 is not exist, provide it before testing!</h1>
  }

  renderAccountsSelect() {
    const { accounts, from } = this.state

    return (
      <select
        value={from}
        disabled={accounts.length === 0}
        onChange={this.onChangeInputByName('from')}
      >
        <option value="" disabled>
          Select account
        </option>
        {accounts.map(account => (
          <option key={account} value={account}>
            {account}
          </option>
        ))}
      </select>
    )
  }

  renderSignForm() {
    const { from, message, signature } = this.state

    return (
      <Fragment>
        <h1>Sign</h1>
        <section>{this.renderAccountsSelect()}</section>
        <section>
          <input
            value={from}
            type="text"
            placeholder="Or enter it manually"
            onChange={this.onChangeInputByName('from')}
          />
        </section>
        <section>
          <textarea
            disabled={!from}
            value={message}
            placeholder="Enter message to sign..."
            onChange={this.onChangeInputByName('message')}
          />
          <textarea
            value={signature}
            placeholder="Signed data..."
            onChange={this.onChangeInputByName('signature')}
          />
        </section>
        <section>
          <button onClick={this.requestAccount}>Request account</button>
        </section>
        <section>
          <span>Signing with eth_sign:</span>
          <button disabled={!from || !message} onClick={this.sign}>
            Sign
          </button>
        </section>
        <section>
          <span>Personal signing:</span>
          <button disabled={!from || !message} onClick={this.personalSign}>
            Personal sign
          </button>
          <button disabled={!signature} onClick={this.verify}>
            Verify
          </button>
        </section>
        <section>
          <span>Reset form:</span>
          <button onClick={this.reset}>Reset</button>
        </section>
      </Fragment>
    )
  }

  render() {
    const { error } = this.state

    return (
      <div className="dapp">
        {error ? this.renderWeb3Error() : this.renderSignForm()}
      </div>
    )
  }
}

export default App

// src/App.vue
<script>
export default {
  data: () => ({
    from: '',
    message: '',
    signature: '',
    accounts: [],
    error: false,
  }),

  created() {
    Notification.requestPermission()

    this.checkWeb3()
  },

  methods: {
    checkWeb3() {
      const { web3 } = window

      if (!web3) {
        this.error = true
        return
      }

      if (web3.eth.accounts.length === 0) {
        console.info(
          'Your web3 has not any accounts. Enter some manually or request it.'
        )
        return
      }

      this.accounts = web3.eth.accounts || []
    },

    errorNotification() {
      new Notification('Action denied', {
        body: 'An error occured, see console for more details',
      })
    },

    verify() {
      window.web3.currentProvider.sendAsync(
        {
          method: 'personal_ecRecover',
          params: [this.message, this.signature],
        },
        (err, { result }) => {
          if (err) {
            this.errorNotification()
            console.error(err)
            return
          }

          alert(`Recovered address: ${result}`)
        }
      )
    },

    sign() {
      window.web3.currentProvider.sendAsync(
        {
          method: 'eth_sign',
          params: [this.from, window.web3.toHex(this.message)],
        },
        (err, { result }) => {
          if (err) {
            this.errorNotification()
            console.error(err)
            return
          }

          this.signature = result
        }
      )
    },

    personalSign() {
      window.web3.currentProvider.sendAsync(
        {
          method: 'personal_sign',
          params: [this.from, window.web3.toHex(this.message)],
        },
        (err, { result }) => {
          if (err) {
            this.errorNotification()
            console.error(err)
            return
          }

          this.signature = result
        }
      )
    },

    requestAccount() {
      window.web3.currentProvider.sendAsync(
        {
          method: 'eth_accounts',
          params: [],
        },
        (err, { result }) => {
          if (err) {
            this.errorNotification()
            console.error(err)
            return
          }

          this.accounts = result
          this.from = result[0]
        }
      )
    },

    reset() {
      this.message = ''
      this.signature = ''
    },
  },
}
</script>

<template>
  <div class="dapp">
    <template v-if="!error">
      <h1>Sign</h1>
      <section>
        <select
          v-model="from"
          :disabled="accounts.length === 0"
        >
          <option
            value=""
            disabled
          >
            Select account
          </option>
          <option
            v-for="account in accounts"
            :key="account"
            :value="account"
          >
            {{ account }}
          </option>
        </select>
      </section>
      <section>
        <input
          v-model="from"
          type="text"
          placeholder="Or enter it manually"
        >
      </section>
      <section>
        <textarea
          v-model="message"
          :disabled="!from"
          placeholder="Enter message to sign..."
        />
        <textarea
          v-model="signature"
          placeholder="Signed data..."
          readonly
        />
      </section>
      <section>
        <button @click="requestAccount">
          Request account
        </button>
      </section>
      <section>
        Signing with eth_sign:
        <button
          :disabled="!from || !message"
          @click="sign"
        >
          Sign
        </button>
      </section>
      <section>
        Personal signing:
        <button
          :disabled="!from || !message"
          @click="personalSign"
        >
          Personal sign
        </button>
        <button
          :disabled="!signature"
          @click="verify"
        >
          Verify
        </button>
      </section>
      <section>
        Reset form:
        <button @click="reset">Reset</button>
      </section>
    </template>
    <h1 v-else>Web3 is not exist, provide it before testing!</h1>
  </div>
</template>

<style>
body {
  font-family: monospace;
  background-color: #efdb21;
}
</style>

<style scoped lang="postcss">
.dapp {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translateX(-50%) translateY(-50%);
  max-width: 480px;
  padding: 15px;
  border: 1px solid #000;
  text-align: center;
  background-color: #ffec44;
}

.dapp section {
  margin-bottom: 10px;
}

.dapp input,
.dapp select {
  width: 100%;
  box-sizing: border-box;
}

.dapp textarea {
  width: 200px;
  height: 300px;
  resize: none;
}
</style>
